package com.example.sungwon.usaepaysandbox;

import android.app.Instrumentation;
import android.os.Bundle;
import android.support.v7.app.AppCompatActivity;
import android.util.Log;
import android.view.KeyEvent;
import android.view.MenuItem;
import android.view.View;
import android.widget.AdapterView;
import android.widget.ArrayAdapter;
import android.widget.Button;
import android.widget.EditText;
import android.widget.Spinner;
import android.widget.TextView;
import android.widget.Toast;

import com.ebizcharge.sdk.Gateway;
import com.ebizcharge.sdk.classes.Address;
import com.ebizcharge.sdk.classes.Customer;
import com.ebizcharge.sdk.classes.OnGatewayResultListener;

import java.util.ArrayList;

public class CustomerSettingActivity extends AppCompatActivity {

    Spinner mTypeofCust;

    EditText mCustomerid;
    TextView mCustomerNum;
    EditText mAddress;
    EditText mZipcode;
    TextView mDateCreated;
    EditText mNotes;
    EditText mCusturl;

    Button mAddcc;
    Button mAddcust;

    String mOption = "add new";
    Boolean mCustNew = false;
    int currentposition = 0;

    ArrayList<Customer> mCustArray = new ArrayList<>();
    ArrayAdapter<CharSequence> adapter;

    @Override
    protected void onCreate(Bundle savedInstanceState) {
        super.onCreate(savedInstanceState);
        setContentView(R.layout.activity_customer_setting);
        getSupportActionBar().setDisplayHomeAsUpEnabled(true);
        Gateway gateway = new Gateway(PaymentLibraryConstants.SOURCE_KEY, PaymentLibraryConstants.SOURCE_PIN, mListener);
        gateway.setSandboxMode(PaymentLibraryConstants.SANDBOX_MODE);
        gateway.getCustomers();
        setupView();
    }

    private void setupView() {
        final Gateway gateway = new Gateway(PaymentLibraryConstants.SOURCE_KEY, PaymentLibraryConstants.SOURCE_PIN, mListener);
        gateway.setSandboxMode(PaymentLibraryConstants.SANDBOX_MODE);
//        ArrayList<String> spinarray = new ArrayList<>();
//        for (int i = 0; i < mCustArray.size(); i++) {
//            spinarray.add(i, String.valueOf(mCustArray.get(i).getCustomerId()));
//            if(i==mCustArray.size()-1){
//                spinarray.add(i+1, "add new");
//            }
//        }
//        mTypeofCust = (Spinner)findViewById(R.id.typeofCust);
//        adapter = new ArrayAdapter<CharSequence>(this, android.R.layout.simple_spinner_item);
//        adapter.setDropDownViewResource(android.R.layout.simple_spinner_dropdown_item);
//        adapter.addAll(spinarray);
//        mTypeofCust.setAdapter(adapter);
        mCustomerid = (EditText)findViewById(R.id.customerid);
        mCustomerNum = (TextView)findViewById(R.id.customerNum);
        mAddress = (EditText)findViewById(R.id.address);
        mZipcode = (EditText)findViewById(R.id.zipcode);
        mDateCreated = (TextView)findViewById(R.id.dateCreated);
        mNotes = (EditText)findViewById(R.id.notes);
        mCusturl = (EditText)findViewById(R.id.custurl);
        mAddcc = (Button)findViewById(R.id.addcc);
        mAddcust = (Button)findViewById(R.id.addcust);

//        mTypeofCust.setOnItemSelectedListener(new AdapterView.OnItemSelectedListener() {
//            @Override
//            public void onItemSelected(AdapterView<?> parent, View view, int position, long id) {
//                mOption = parent.getItemAtPosition(position).toString();
//                if(mOption.equals("add new")){
//                    mCustomerNum.setText("Generated by Gateway");
//                    mDateCreated.setText("Generated by Gateway");
//                    mCustNew = true;
//                } else {
//                    mCustomerid.setText(String.valueOf(mCustArray.get(position).getCustomerId()));
//                    mCustomerNum.setText(String.valueOf(mCustArray.get(position).getCustomerNumber()));
//                    mAddress.setText(mCustArray.get(position).getBillingAddress().getStreet());
//                    mZipcode.setText(mCustArray.get(position).getBillingAddress().getZip());
//                    mDateCreated.setText(mCustArray.get(position).getDateCreated().toString());
//                    mNotes.setText(mCustArray.get(position).getNotes());
//                    mCusturl.setText(mCustArray.get(position).getUrl());
//                    mCustNew = false;
//                    currentposition = position;
//                }
//            }
//
//            @Override
//            public void onNothingSelected(AdapterView<?> parent) {
//                mOption = "add new";
//                mCustomerNum.setText("Generated by Gateway");
//                mDateCreated.setText("Generated by Gateway");
//                mCustNew = true;
//            }
//        });
        mAddcust.setOnClickListener(new View.OnClickListener() {
            @Override
            public void onClick(View v) {
                if(mCustNew) {
                    Customer customer = new Customer();
                    customer.setCustomerId(Long.parseLong(mCustomerid.getText().toString()));
                    Address address = new Address();
                    address.setStreet(mAddress.getText().toString());
                    address.setZip(mZipcode.getText().toString());
                    customer.setBillingAddress(address);
                    customer.setNotes(mNotes.getText().toString());
                    customer.setUrl(mCusturl.getText().toString());
                    gateway.addCustomer(customer);
                } else{
                    Customer customer = mCustArray.get(currentposition);
                    customer.setCustomerId(Long.parseLong(mCustomerid.getText().toString()));
                    Address address = customer.getBillingAddress();
                    address.setStreet(mAddress.getText().toString());
                    address.setZip(mZipcode.getText().toString());
                    customer.setBillingAddress(address);
                    customer.setNotes(mNotes.getText().toString());
                    customer.setUrl(mCusturl.getText().toString());
                    gateway.updateCustomer(customer);
                }
            }
        });
    }

    private OnGatewayResultListener mListener = new OnGatewayResultListener() {
        @Override
        public void onGatewayResult(int requestCode, int resultCode, Bundle data) {
            if (resultCode == Gateway.RESULT_OK) {
                if(requestCode == Gateway.GET_CUSTOMERS) {
                    mCustArray = data.getParcelableArrayList(Gateway.EXTRA_RESULT);
                    Log.d("CustSetting", "Customer get success");
                    new Thread(new Runnable() {
                        @Override
                        public void run() {
                            try{
                                Instrumentation inst = new Instrumentation();
                                Thread.sleep(200);
                                inst.sendKeyDownUpSync(KeyEvent.KEYCODE_DPAD_LEFT);
                            }catch(Exception e){

                            }
                        }
                    }).start();
                } else if(requestCode == Gateway.ADD_CUSTOMER){
                    //code after added
                } else if(requestCode == Gateway.UPDATE_CUSTOMER){
                }

            } else { // resultCode == Gateway.RESULT_ERROR
                Bundle b = new Bundle();

                b.putParcelable(PaymentLibraryConstants.GATEWAY_EXCEPTION,
                        data.getParcelable(Gateway.EXTRA_EXCEPTION));
                Toast.makeText(CustomerSettingActivity.this, "Gateway Error", Toast.LENGTH_SHORT).show();
            }
        }
    };

    @Override
    public boolean onOptionsItemSelected(MenuItem item) {
        switch (item.getItemId()) {
            case android.R.id.home:
                finish();
                return true;
        }
        return super.onOptionsItemSelected(item);
    }

    @Override
    public boolean onKeyUp(int keyCode, KeyEvent event) {
        switch (keyCode){
            case KeyEvent.KEYCODE_DPAD_LEFT:
                ArrayList<String> spinarray = new ArrayList<>();
                for (int i = 0; i < mCustArray.size(); i++) {
                    spinarray.add(i, String.valueOf(mCustArray.get(i).getCustomerId()));
                    if(i==mCustArray.size()-1){
                        spinarray.add(i+1, "add new");
                    }
                }
                mTypeofCust = (Spinner)findViewById(R.id.typeofCust);
                adapter = new ArrayAdapter<CharSequence>(this, android.R.layout.simple_spinner_item);
                adapter.setDropDownViewResource(android.R.layout.simple_spinner_dropdown_item);
                adapter.addAll(spinarray);
                mTypeofCust.setAdapter(adapter);
                mTypeofCust.setOnItemSelectedListener(new AdapterView.OnItemSelectedListener() {
                    @Override
                    public void onItemSelected(AdapterView<?> parent, View view, int position, long id) {
                        mOption = parent.getItemAtPosition(position).toString();
                        if(mOption.equals("add new")){
                            mCustomerNum.setText("Generated by Gateway");
                            mDateCreated.setText("Generated by Gateway");
                            mCustomerid.setText(position);
                            mAddress.setText("");
                            mZipcode.setText("");
                            mNotes.setText("");
                            mCusturl.setText("");
                            mCustNew = true;
                        } else {
                            mCustomerid.setText(String.valueOf(mCustArray.get(position).getCustomerId()));
                            mCustomerNum.setText(String.valueOf(mCustArray.get(position).getCustomerNumber()));
                            mAddress.setText(mCustArray.get(position).getBillingAddress().getStreet());
                            mZipcode.setText(mCustArray.get(position).getBillingAddress().getZip());
                            mDateCreated.setText(mCustArray.get(position).getDateCreated().toString());
                            mNotes.setText(mCustArray.get(position).getNotes());
                            mCusturl.setText(mCustArray.get(position).getUrl());
                            mCustNew = false;
                            currentposition = position;
                        }
                    }

                    @Override
                    public void onNothingSelected(AdapterView<?> parent) {
                        mOption = "add new";
                        mCustomerNum.setText("Generated by Gateway");
                        mDateCreated.setText("Generated by Gateway");
                        mCustNew = true;
                    }
                });
                return true;
            default:
                return super.onKeyUp(keyCode, event);
        }
    }
}
